plugins {
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'org.spongepowered.mixin' version '0.7.+'
    // https://plugins.gradle.org/plugin/me.modmuss50.mod-publish-plugin
    id 'me.modmuss50.mod-publish-plugin' version '1.0.0'
    // https://plugins.gradle.org/plugin/se.bjurr.gitchangelog.git-changelog-gradle-plugin
    id 'se.bjurr.gitchangelog.git-changelog-gradle-plugin' version '3.0.7'
    id 'io.freefair.lombok' version '8.14.2'
}

repositories {
    maven {
        // location of the maven that hosts Mantle and JEI files
        name = 'Progwml6 maven'
        url = 'https://dvs1.progwml6.com/files/maven'
    }
    maven {
        name = 'BlameJared Maven (CrT / Bookshelf / JEI (Newer) / vazkii / xyz)'
        url = 'https://maven.blamejared.com'
    }
    maven { // TOP
        name 'McJty maven'
        url "https://maven.k-4u.nl"
    }
    maven {
        name = 'Curse Maven'
        url = 'https://cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
}

group = 'com.github.wendall911.tinkersurvival'
def actualVersion = version
version = "${minecraft_version}-${version}"
archivesBaseName = "${mod_name}"

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '17'

minecraft {
    mappings channel: 'parchment', version: "${mappings_version}-${minecraft_version}"

    runs {
        client {
            workingDirectory project.file("run").canonicalPath
            arg "-mixin.config=${mod_id}.mixins.json"
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                tinkersurvival {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            arg "-mixin.config=${mod_id}.mixins.json"
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                tinkersurvival {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            arg "-mixin.config=${mod_id}.mixins.json"
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            args '--mod', 'tinkersurvival',
                    '--all',
                    '--output', file('src/generated/resources/'),
                    '--existing', file('src/main/resources/'),
                    '--existing', file('src/generated/resources')

            mods {
                tinkersurvival {
                    source sourceSets.main
                }
            }
        }
    }
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    annotationProcessor "org.spongepowered:mixin:${mixin_version}:processor"

    implementation fg.deobf("slimeknights.mantle:Mantle:${minecraft_version}-${mantle_version}")
    implementation fg.deobf("slimeknights.tconstruct:TConstruct:${minecraft_version}-${tic_version}")

    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    implementation fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")

    runtimeOnly fg.deobf("mcjty.theoneprobe:theoneprobe:${minecraft_short_version}-${probe_version}") {
        transitive = false
    }

    compileOnly fg.deobf("curse.maven:carryon-274259:3674344")

    if (System.getenv('DATA_GEN') == null) {
        //runtimeOnly fg.deobf("curse.maven:crafttweaker-239197:3918220")

        //Include some examples here for testing other mods
        //runtimeOnly fg.deobf("curse.maven:sushigocrafting-452500:3758195")
        //runtimeOnly fg.deobf("curse.maven:titanium-287342:3707558")
        //runtimeOnly fg.deobf("curse.maven:patchouli-306770:${patchouli_version}")
        //runtimeOnly fg.deobf("curse.maven:curios-309927:${curios_version}")
        //implementation fg.deobf("curse.maven:botania-225643:${botania_version}")
        //implementation fg.deobf("curse.maven:immersiveengineering-231951:${ie_version}")
        //runtimeOnly fg.deobf("curse.maven:buildinggadgets-298187:3725903")
        //runtimeOnly fg.deobf("curse.maven:homeostatic-634466:3845248")
        //runtimeOnly fg.deobf("curse.maven:twilightforest-227639:3901400")
        //runtimeOnly fg.deobf("curse.maven:oreganized-439153:3819472")
        //runtimeOnly fg.deobf("curse.maven:macawswindows-363569:3712019")
        //runtimeOnly fg.deobf("curse.maven:configured-457570:3721946")
        //runtimeOnly fg.deobf("curse.maven:catalogue-459701:3803098")
        //runtimeOnly fg.deobf("curse.maven:electrodynamics-316867:3784685")
        //runtimeOnly fg.deobf("curse.maven:valhesia_core-416935:3768769")
        //runtimeOnly fg.deobf("curse.maven:valhesia_structures-347488:3708292")
        //runtimeOnly fg.deobf("curse.maven:geckolib-388172:${geckolib_version}")
        //implementation fg.deobf("curse.maven:arsnouveau-401955:${arsnouveau_version}")
        //runtimeOnly fg.deobf("curse.maven:exnihilo-400012:3874541")
        //implementation fg.deobf("curse.maven:undergarden-379849:${undergarden_version}")
        //runtimeOnly fg.deobf("curse.maven:dynamictrees-252818:3831578")
        //runtimeOnly fg.deobf("curse.maven:terrablender-563928:${terrablender_version}")
        //implementation fg.deobf("curse.maven:byg-247560:${byg_version}")
        //runtimeOnly fg.deobf("curse.maven:ecologics-570463:3939725")
        //runtimeOnly fg.deobf("curse.maven:lodestone-616457:4616315")
        //runtimeOnly fg.deobf("curse.maven:malum-484064:4631612")
        //runtimeOnly fg.deobf("curse.maven:citadel-331936:3783096")
        //runtimeOnly fg.deobf("curse.maven:iceandfire-264231:4614465")
    }
}

def commonManifest = {
    attributes 'FMLAT': 'tinkersurvival_at.cfg'
}

jar {
    manifest {
        attributes([
            "Specification-Title": mod_name,
            "Specification-Vendor": "${mod_author}",
            "Specification-Version": "${archiveVersion}",
            "Implementation-Title": "${mod_name}",
            "Implementation-Version": "${archiveVersion}",
            "Implementation-Vendor" :"${mod_author}",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            "MixinConfigs": "${mod_id}.mixins.json"
        ])
    }
}

def resourceTargets = ['META-INF/mods.toml', 'pack.mcmeta', '*.mixins.json']
def replaceProperties = [
    'version': actualVersion, 'forge_mc_version_range': forge_mc_version_range, 'forge_version_range': forge_version_range,
    'license': license, 'mod_id': mod_id, 'mod_author': mod_author, 'mod_description': mod_description,
    'mod_name': mod_name, 'issue_tracker': issue_tracker, 'mod_credits': mod_credits,
    'mod_update_branch': mod_update_branch
]

processResources {
    duplicatesStrategy(DuplicatesStrategy.FAIL)
    inputs.properties replaceProperties
    exclude '.cache'
    replaceProperties.put 'project', project

    filesMatching(resourceTargets) {
        expand replaceProperties
    }
}

jar.finalizedBy('reobfJar')

def updates = tasks.register("generateUpdates", Copy) {
    it.outputs.upToDateWhen {
        false
    }

    it.from("./files/templates/") {
        include 'updates.json'
        expand 'version': actualVersion, 'minecraft_version': minecraft_version
    }

    it.into 'files/'
}

task changelog(type: se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask) {
    file.set(new File(project(":").projectDir.toString() + '/build/libs/changelog.txt'));
    templateContent.set(file(project(":").projectDir.toString() + '/files/templates/changelog.mustache').getText('UTF-8'));
    toRevision.set('HEAD');
    fromRevision.set("${minecraft_version}-${last_mod_version}");
}

tasks.build.dependsOn('changelog', 'generateUpdates')

def changelogFile = project(":").projectDir.toString() + '/build/libs/changelog.txt'
def publishFile = project(":").projectDir.toString() + "/build/libs/${archivesBaseName}-${version}.jar"

publishMods {
    file = file(publishFile)
    if (file(changelogFile).exists()) {
        changelog = file(changelogFile).text
    }
    type = "${release_type}".startsWith("release") ? STABLE : ("${release_type}".startsWith("beta") ? BETA : ALPHA)
    modLoaders.addAll(['forge'])
    dryRun = providers.environmentVariable('DO_RELEASE').getOrNull() == null

    if (project.hasProperty('tscurseApiKey')) {
        curseforge {
            accessToken = project.tscurseApiKey
            projectId = project.tscurseId
            projectSlug = project.tsSlug
            javaVersions.add(JavaVersion.toVersion("${java_version}"))
            clientRequired = true
            serverRequired = true
            minecraftVersions.addAll("${release_versions}".split(','))
            requires('mantle')
            requires('tinkers-construct')
            optional('configured')
            optional('catalogue')
            optional('fruit-trees')
            optional('quark')
            optional('biomes-o-plenty')
            optional('all-you-can-eat')
            optional('water-source')
            optional('sushigocrafting')
            optional('botania')
            optional('ars-nouveau')
            optional('exnihilosequentia')
            optional('the-undergarden')
            optional('dynamictrees')
            optional('oh-the-biomes-youll-go')
            optional('the-twilight-forest')
            optional('ecologics')
            optional('malum')
            optional('ice-and-fire-dragons')
        }
    }
    if (project.hasProperty('tsModrinthId')) {
        modrinth {
            accessToken = project.modrinthKey
            projectId = project.tsModrinthId
            minecraftVersions.addAll("${release_versions}".split(','))
            requires('mantle')
            requires('tinkers-construct')
            optional('quark')
            optional('allyoucaneat')
            optional('botania')
            optional('exnihilosequentia')
            optional('dynamictrees')
            optional('biomesyougo')
            optional('ecologics')
        }
    }
    if (project.hasProperty('tsDiscordWebhook')) {
        discord {
            webhookUrl = project.tsDiscordWebhook
            dryRunWebhookUrl = project.discordDryrunWebhook
            username = "wendall911"
            content = changelog.map {
                "# A new version of Tinkers' Survival for Forge ${minecraft_version} has been released! \n" + it
            }
        }
    }
}
