plugins {
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
    id 'se.bjurr.gitchangelog.git-changelog-gradle-plugin' version '1.71.8'
    id 'io.freefair.lombok' version '6.3.0'
    id 'me.modmuss50.mod-publish-plugin' version '0.7.3'
}

repositories {
    maven {
        // location of the maven that hosts Mantle and JEI files
        name = 'Progwml6 maven'
        url = 'https://dvs1.progwml6.com/files/maven'
    }
    maven { // TOP
        name 'McJty maven'
        url "https://maven.k-4u.nl"
    }
    maven { // CraftTweaker, Immersive Engineering, JEI
        name 'BlameJared Maven'
        url 'https://maven.blamejared.com'
    }
    flatDir {
        dirs 'libs'
    }
    maven {
        name = "Curse Maven"
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
	maven {
		name = "C4's Maven"
		url = "https://maven.theillusivec4.top/"
	}
    maven {
        // Patchouli && Provider
        name = "Blame Jared"
        url = "https://maven.blamejared.com"
    }
}

group = 'com.github.wendall911.tinkersurvival'
version = "${minecraft_version}-${mod_version}"
archivesBaseName = "${mod_name}"
def mcversion = "${minecraft_version}"
def modid = "${modid}"

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '17'

minecraft {
    mappings channel: "${mappings_channel}", version: "${mappings_version}-${minecraft_version}"

    runs {
        client {
            workingDirectory project.file("run").canonicalPath
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                tinkersurvival {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            mods {
                tinkersurvival {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            args '--mod', 'tinkersurvival',
                    '--all',
                    '--output', file('src/generated/resources/'),
                    '--existing', file('src/main/resources/'),
                    '--existing', file('src/generated/resources')

            mods {
                tinkersurvival {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    implementation fg.deobf("slimeknights.mantle:Mantle:${minecraft_version}-${mantle_version}")
    implementation fg.deobf("slimeknights.tconstruct:TConstruct:${minecraft_version}-${tic_version}")
    implementation fg.deobf("curse.maven:se-676800:${se_version}")
    implementation fg.deobf("curse.maven:homeostatic-634466:${homeostatic_version}")
    implementation fg.deobf("vazkii.patchouli:Patchouli:${patchouli_version}-FORGE")
    implementation fg.deobf("xyz.brassgoggledcoders:PatchouliProvider:${patchouli_provider_version}")
    implementation fg.deobf("curse.maven:chargedcharms-682683:${chargedcharms_version}")

    if (System.getenv('DATA_GEN') == null) {
        //Include some examples here for testing other mods
        runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")
        runtimeOnly fg.deobf("mcjty.theoneprobe:theoneprobe:${minecraft_version}-${probe_version}") {
            transitive = false
        }
        runtimeOnly fg.deobf("curse.maven:botania-225643:${botania_version}")
        runtimeOnly fg.deobf("curse.maven:immersiveengineering-231951:${ie_version}")
        runtimeOnly fg.deobf("curse.maven:sol_carrot-277616:${sol_carrot_version}")
        runtimeOnly fg.deobf("curse.maven:titanium-287342:${titanium_version}")
        runtimeOnly fg.deobf("curse.maven:sushigocrafting-452500:${sushigocrafting_version}")
        runtimeOnly fg.deobf("curse.maven:culinary_construct-296676:${culinary_construct_version}")
        runtimeOnly fg.deobf("curse.maven:architectury-419699:${architectury_version}")
        runtimeOnly fg.deobf("curse.maven:bmo-567709:${bmo_version}")
    }
    else {
        runtimeOnly fg.deobf("curse.maven:create-328085:${create_version}")
    }

	runtimeOnly fg.deobf("top.theillusivec4.curios:curios-forge:${curios_version}+${minecraft_version}")
    runtimeOnly fg.deobf("curse.maven:comforts-276951:${comforts_version}")

    implementation fg.deobf(fileTree(dir: 'libs', include: '*.jar'))
}

def commonManifest = {
    attributes 'FMLAT': 'tinkersurvival_at.cfg'
}

jar {
    manifest {
        attributes([
            "Specification-Title": mod_name,
            "Specification-Vendor": "${mod_author}",
            "Specification-Version": "${archiveVersion}",
            "Implementation-Title": "${mod_name}",
            "Implementation-Version": "${archiveVersion}",
            "Implementation-Vendor" :"${mod_author}",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

def resourceTargets = ['META-INF/mods.toml', 'pack.mcmeta']
def replaceProperties = [ 'version': version,
    'issue_tracker': issue_tracker, 'license': license, 'modid': modid, 'display_name': display_name,
    'description': description, 'display_url': display_url, 'update_url': update_url, 'authors': authors,
    'credits': credits, 'logo_file': logo_file, 'minecraft_version_range': minecraft_version_range,
    'forge_version_range': forge_version_range, "loader_version_range": loader_version_range,
    'se_full_version': se_full_version
]

processResources {
    duplicatesStrategy(DuplicatesStrategy.FAIL)
    inputs.properties replaceProperties
    exclude '.cache'
    replaceProperties.put 'project', project

    filesMatching(resourceTargets) {
        expand replaceProperties
    }
}

jar.finalizedBy('reobfJar', 'signJar')

def updates = tasks.register("generateUpdates", Copy) {
    it.outputs.upToDateWhen {
        false
    }

    it.from("./files/templates/") {
        include 'updates.json'
        expand 'mod_version': mod_version
    }

    it.into 'files/'
}

def changelogFile = project(":").projectDir.toString() + '/build/libs/' + project.getName() + '-' + version + '-changelog.txt'
def publishFile = project(":").projectDir.toString() + "/build/libs/${archivesBaseName}-${version}.jar"

publishMods {
    file = file(publishFile)
    if (file(changelogFile).exists()) {
        changelog = file(changelogFile).text
    }
    type = "${release_type}".startsWith("release") ? STABLE : ("${release_type}".startsWith("beta") ? BETA : ALPHA)
    modLoaders.addAll(['forge'])

    if (project.hasProperty('tscurseApiKey')) {
        curseforge {
            accessToken = project.tscurseApiKey
            projectId = project.tscurseId
            javaVersions.add(JavaVersion.toVersion("${java_version}"))
            clientRequired = true
            serverRequired = true
            minecraftVersions.addAll("${release_versions}".split(','))
            embeds('spectrelib')
            requires('mantle')
            requires('tinkers-construct')
            optional('configured')
            optional('catalogue')
            optional('fruit-trees')
            optional('quark')
            optional('biomes-o-plenty')
            optional('all-you-can-eat')
            optional('water-source')
            optional('sushigocrafting')
            optional('botania')
            optional('ars-nouveau')
            optional('exnihilosequentia')
            optional('the-undergarden')
            optional('dynamictrees')
            optional('oh-the-biomes-youll-go')
            optional('the-twilight-forest')
            optional('ecologics')
            optional('alexs-mobs')
            optional('betteranimalsplus')
            optional('malum')
            optional('ice-and-fire-dragons')
            optional('psi')
        }
    }
    if (project.hasProperty('tsModrinthId')) {
        modrinth {
            accessToken = project.modrinthKey
            projectId = project.tsModrinthId
            minecraftVersions.addAll("${release_versions}".split(','))
            requires('mantle')
            requires('tinkers-construct')
			requires('quark')
            requires('allyoucaneat')
            requires('botania')
            requires('exnihilosequentia')
            requires('dynamictrees')
            requires('biomesyougo')
            requires('ecologics')
            requires('psi')
        }
    }
    if (project.hasProperty('tsGithubToken')) {
    }
}

task changelog(type: se.bjurr.gitchangelog.plugin.gradle.GitChangelogTask) {
    file = new File(changelogFile);
    templateContent = file('files/templates/changelog.mustache').getText('UTF-8');
    fromRepo = file("$projectDir");
    toRef = "HEAD";
    fromRef = "${minecraft_version}-${last_mod_version}";
}

tasks.build.dependsOn('changelog', 'generateUpdates')

// Jar Signing
import net.minecraftforge.gradle.common.tasks.SignJar

task signJar(type: SignJar, dependsOn: jar) {
    dependsOn 'reobfJar'

    // Skip the task if our secret data isn't available
    onlyIf {
        project.hasProperty('keyStore')
    }

    keyStore = project.keyStore // This needs to be a path to the keystore file
    alias = project.keyStoreAlias
    storePass = project.keyStorePass
    keyPass = project.keyStoreKeyPass
    inputFile = jar.archiveFile
    outputFile = jar.archiveFile
}

publishing {
    repositories {
        maven {
            name = 'GitHubPackages'
            url = uri(maven_url)
            credentials {
                username = project.githubusername
                password = project.githubtoken
            }
        }
    }

    publications {
        gpr(MavenPublication) {
            artifactId = modid
            from(components.java)
        }
    }
}
