# Gradle
org.gradle.jvmargs=-Xmx2048M
org.gradle.daemon=false

# Project
mod_name=TinkerSurvival
modid=tinkersurvival
mod_version=5.0.0.0
last_mod_version=4.1.1.7
java_version=17

# Common
minecraft_version=1.20.1
minecraft_short_version=1.20
minecraft_version_range=[1.20,1.20.2)

# Forge
loader_version_range=[46,)
forge_version=47.3.12
forge_version_range=[46.0.0,)

# Mappings
mappings_version=2023.09.03
mappings_channel=parchment

# Mod options
mod_author=wendall911
issue_tracker=https://github.com/wendall911/TinkerSurvival/issues
license=MIT
display_name=Tinkers' Survival
description=A small mod to make the first day or two of play more believable. New early game tools, Tinkers' Construct tools, and more!
display_url=https://github.com/wendall911/TinkerSurvival
update_url=https://raw.githubusercontent.com/wendall911/TinkerSurvival/1.20.1/files/updates.json
authors=wendall911
credits=ashar42 billyzekat
logo_file=logo.png
maven_url=https://maven.pkg.github.com/wendall911/TinkerSurvival

# CurseForge/Modrinth Options
release_type=release
release_versions=1.20.1

# Integration Mods
jei_version=15.20.0.103
mantle_version=1.11.44
tic_version=3.9.2.37
se_version=6345959
se_full_version=1.20.1-6.2.1.2
homeostatic_version=5906079
patchouli_version=1.20.1-83
patchouli_provider_version=1.20.1-1.0.9-Snapshot.1
probe_version=10.0.1-3
comforts_version=5503516
botania_version=6172172
create_version=5838779
ie_version=6206989
curios_version=5.9.1
sol_carrot_version=4888575
titanium_version=5468426
sushigocrafting_version=5638169
culinary_construct_version=4814120
chargedcharms_version=5625248
bmo_version=4815822
architectury_version=5137938
