# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=5.0.0.2
last_mod_version=5.0.0.1

# Common
minecraft_version=1.20.1
minecraft_short_version=1.20
java_version=17

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2023.09.03

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=47.4.8
forge_version_range=[46,)
forge_mc_version_range=[1.20,1.20.2)

# Integration Mods
jei_version=15.20.0.112
mantle_version=1.11.79
tic_version=3.10.2.92
se_full_version=1.20.1-6.2.3.5
homeostatic_version=6990775
patchouli_version=1.20.1-83
patchouli_provider_version=1.20.1-1.0.9-Snapshot.1
probe_version=6106996
comforts_version=5503516
botania_version=6172172
create_version=5838779
ie_version=6206989
curios_version=5.9.1
sol_carrot_version=4888575
titanium_version=5468426
sushigocrafting_version=5638169
culinary_construct_version=4814120
chargedcharms_version=5625248
bmo_version=4815822
architectury_version=5137938

# Mod options
mod_name=TinkerSurvival
mod_id=tinkersurvival
mod_author=wendall911
mod_credits=ashar42 billyzekat
license=MIT
issue_tracker=https://github.com/wendall911/TinkerSurvival/issues
mod_description=A small mod to make the first day or two of play more believable. New early game tools, Tinkers' Construct tools, and more!
mod_update_branch=1.20.1

# CurseForge/Modrinth Options
release_type=release
release_versions=1.20.1
