# Gradle
org.gradle.jvmargs=-Xmx2048M
org.gradle.daemon=false

# Project
mod_name=TinkerSurvival
modid=tinkersurvival
mod_version=4.1.1.7
last_mod_version=4.1.1.6
java_version=17

# Common
minecraft_version=1.19.2
minecraft_short_version=1.19
minecraft_version_range=[1.19.2,1.19.3)

# Forge
loader_version_range=[41,)
forge_version=43.3.0
forge_version_range=[43.3.0,)

# Mappings
mappings_version=2022.11.27
mappings_channel=parchment

# Mod options
mod_author=wendall911
issue_tracker=https://github.com/wendall911/TinkerSurvival/issues
license=MIT
display_name=Tinkers' Survival
description=A small mod to make the first day or two of play more believable. New early game tools, Tinkers' Construct tools, and more!
display_url=https://github.com/wendall911/TinkerSurvival
update_url=https://raw.githubusercontent.com/wendall911/TinkerSurvival/1.18.2/files/updates.json
authors=wendall911
credits=ashar42 billyzekat
logo_file=logo.png
maven_url=https://maven.pkg.github.com/wendall911/TinkerSurvival

# CurseForge/Modrinth Options
release_type=release
release_versions=1.19.2

# Integration Mods
jei_version=11.6.+
mantle_version=1.10.48
tic_version=3.8+
se_version=1.19.2-4.+
homeostatic_version=1.19.2-2.9+
patchouli_version=1.19.2-77
patchouli_provider_version=1.19-1.0.7-Snapshot.2
probe_version=6.2.0-6
comforts_version=4977779
botania_version=4557912
create_version=4835190
ie_version=5222176
curios_version=5302436
sol_carrot_version=3974155
titanium_version=5151215
sushigocrafting_version=4015895
culinary_construct_version=4814066
chargedcharms_version=5200681
bmo_version=4467758
architectury_version=5137942
