modLoader="javafml"
loaderVersion="${forge_version_range}"
license="${license}"
logoBlur=false
issueTrackerURL="${issue_tracker}"

[[mods]]
    modId="${modid}"
    displayName="${display_name}"
    description="${description}"
    version="${version}"
    displayURL="${display_url}"
    updateJSONURL="https://raw.githubusercontent.com/wendall911/TinkerSurvival/${mod_update_branch}/files/updates.json"
    authors="${authors}"
    credits="${credits}"
    itemIcon="tinkersurvival:rock_stone"
    logoFile="${logo_file}"
[[dependencies.${modid}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modid}]]
    modId="minecraft"
    mandatory=true
    versionRange="${forge_mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${modid}]]
    modId="tconstruct"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${modid}]]
    modId="survivalistessentials"
    mandatory=true
    versionRange="[${se_full_version},)"
    ordering="AFTER"
    side="BOTH"
